---
- name: Deploy MERN application
  hosts: deployment
  become: yes
  tasks:
    - name: Pull latest code from Git
      git:
        repo: 'https://github.com/hiramure/DevOps-project.git'
        dest: /home/sayuri/Desktop/Samasthi
        version: HEAD

    - name: Build and start Docker containers
      shell: docker-compose -f /home/deployuser/app/docker-compose.yml up -d --build
      args:
        chdir: /home/deployuser/app
